POST http://localhost:9001/api/categorias HTTP/1.1
content-Type: application/json

{
    "nombre_categoria": "Silleteria",
    "descripcion": "Categoría dedicada a silleteria",
    "estado": "activo"
}
###
GET http://localhost:9001/api/categorias HTTP/1.15


###
GET http://localhost:9001/api/categorias/673d2b0d440d656c67672021 HTTP/1.1

###
PUT http://localhost:9001/api/categorias/673cdefc75a9ff5b9100271d HTTP/1.1
Content-Type: application/json

{
    "nombre_categoria": "Puertas",
    "descripcion": "Categoría dedicada a productos puertas trafic",
    "estado": "activo"
}

###
DELETE http://localhost:9001/api/categorias/67352e2ee4f4071fc562a188 HTTP/1.1
