### 
POST http://localhost:9001/api/detalle_ordenes HTTP/1.1
Content-Type: application/json

{
  "numero_producto": "4",
  "cantidad": 3,
  "precio_unitario": 400000,
  "personalizacion": "techos de 50x45 azul rey.",
  "archivo": "uploads/1677829338473.jpg"
}

### 
GET http://localhost:9001/api/detalle_ordenes HTTP/1.1

### 
GET http://localhost:9001/api/detalle_ordenes/6758af3b803bf5428034dd59 HTTP/1.1

### 
PUT http://localhost:9001/api/detalle_ordenes/673f9098776a53dbe6bcb17f HTTP/1.1
Content-Type: application/json

{
  "numero_orden": "4",
  "numero_producto": 202,
  "cantidad": 2,
  "precio_unitario": 350000,
  "personalizacion": "Silla pequeña y grande, azul y roja.",
  "archivo": "uploads/updated-file.jpg"
}

### 
DELETE http://localhost:9001/api/detalle_ordenes/67352e2ee4f4071fc562a188 HTTP/1.1
